#!/bin/bash

# Find directory that this script is in 
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $SCRIPT_DIR
    # Install vim plugins / submodules
    git submodule update --init --recursive
    python ./extras/YouCompleteMe/install.py --all
    ln -s $(realpath ./extras/YouCompleteMe) ./.vim/bundle/YouCompleteMe
popd

