#!/usr/bin/env bash

##
# Update installation and associated submodules

# Find directory that this script is in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $SCRIPT_DIR

   git pull
   git submodule update --init --recursive
   git submodule foreach --recursive git fetch
   git submodule foreach git merge origin master
   ./install

popd
