#! /usr/bin/env ruby
##
# Install Instructions:
#  cp ./scripts/cvim /usr/local/bin/cvim
#  sudo chmod a+x /usr/local/bin/cvim
#  cp ./scripts/cvim.desktop /usr/share/applications/cvim.desktop
#  sudo update-desktop-database
#
# Test it:
#  xdg-open 'vim:///etc/hosts?line=2'

require 'uri'
require 'cgi'

full_path = ARGV[0]

exit unless full_path

uri = URI::parse(full_path)

exit unless uri.query

params = CGI::parse(uri.query)
file = params['url'].first.sub('file://','')
exit unless file && File.exist?(file)

line = params["line"][0]
vim_params = file 
vim_params << " +#{line.to_i}" if line

`gnome-terminal -x vim #{vim_params}`
