#!/bin/bash

# Connect to ip address and forward access to the vnc server
# By default this command will try to reverse connect to the client
# on port 5500
#/Applications/Vine\ Server.app/OSXvnc-server -connectHost  $1
#x11vnc -quiet -safer -rfbport 0 -xkb -connect_or_exit $1:5500 -display :0

usage() { echo "Usage: $0 [-l <local port to send>] [-r <remote port to receive>] [-a <remote address>] [-p <remote ssh port>]" 1>&2; exit 1; }

while getopts ":l:r:a:p:" o; do
    case "${o}" in
        l)
            l=${OPTARG}
            ;;
        r)
            r=${OPTARG}
            ;;
        a)
            a=${OPTARG}
            ;;
        p)
            p=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${l}" ] || [ -z "${r}" ] || [ -z "${a}" ] || [ -z "${p}" ]; then
    usage
fi

# Forward a local port to the remote machine
# Remote machine will gain access to $FORWARDED_PORT
echo ssh -R ${r}:localhost:${l} $USER@${a} -p ${p}
ssh -R ${r}:localhost:${l} $USER@${a} -p ${p}
